services:
  pg_server:
    container_name: postgres
    image: postgres:12.20-alpine3.19
    restart: always
    ports:
      - "5432:5432"
    expose:
      - "5432"
    volumes:
      - ./postgres:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${PSQL_USER}
      POSTGRES_PASSWORD: ${PSQL_PASS}
      POSTGRES_DB: ${PSQL_DB}
